# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 782d24856d391f57e0866e42ce6a4ec5abe01aa118d7e7cb0612dae8e5f4db6180c624baa15fa34d8e1df5f1585a895d773947be001f1d24587c8477621e2aa6

test:
  secret_key_base: c7d86427375072e04dad50251f8779ab5896d0a8071c0e3246dbeccbcdaee20aebab167de167e86dcee7ea598e081e564e45ac2487209e86570cd60e10f1c0e2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
